name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install PyTorch (required for PyText)
        run: pip install torch torchvision torchaudio

      - name: Install PyText from GitHub
        run: |
          git clone https://github.com/facebookresearch/pytext.git
          cd pytext
          pip install -e .
          cd ..

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pytest
        run: |
          pip install pytest
          pip install hypothesis==6.88.1
      - name: Run tests
        run: pytest
